name: SEPIA-CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'windows-latest' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
        # NOTE: Example for excluding specific python versions for an different OS's.
        # exclude:
        #   - os: windows-latest
        #     python-version: 3.6
        #   - os: macos-latest
        #     python-version: 3.8
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install nbconvert nbformat ipykernel
    - name: Test with unittest
      run: |
        python -m unittest discover -s test
